In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/zalando-research/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_test.csv
/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_train.csv
/kaggle/input/datasets/zalando-research/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/train-images-idx3-ubyte

In [2]:
df = pd.read_csv("/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_train.csv")
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,1,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,8,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df = df-df.mean()
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,-2.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
1,4.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
2,1.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,2.801717,-5.682,...,-34.6254,-23.300683,-16.588267,12.130567,20.185183,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
3,-4.5,-0.0009,-0.00615,-0.035333,0.898067,1.752033,-0.411467,-0.805767,-2.198283,-5.682,...,-31.6254,-23.300683,-16.588267,-17.869433,-22.814817,-16.911483,-8.520633,-2.7533,-0.855517,-0.07025
4,-1.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,4.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59996,-3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,38.3746,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59997,3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,125.3746,138.699317,146.411733,117.130567,71.185183,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59998,3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59999,2.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025

In [4]:
df.mean()

label       0.000000e+00
pixel1      2.442491e-19
pixel2     -7.105427e-19
pixel3     -4.381680e-18
pixel4     -4.357995e-17
                ...
pixel780   -7.351749e-16
pixel781   -1.008023e-15
pixel782   -7.389644e-17
pixel783    0.000000e+00
pixel784   -2.297422e-17
Length: 785, dtype: float64

In [5]:
(df.T@df)/len(df)-df.mean()@df.mean().T

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
label,8.250000,-0.000183,0.002292,-0.036650,-0.050100,-0.057300,-0.185150,-0.867517,-3.449342,-11.052667,...,-59.934533,-36.256492,-22.081300,-11.437067,-11.513658,-8.680242,-1.534300,2.278550,1.611458,0.132942
pixel1,-0.000183,0.008966,0.007644,0.007818,0.010825,0.010860,0.014463,0.009408,0.016305,0.021736,...,-0.003496,0.021396,0.018304,0.004034,-0.011317,-0.010437,-0.000302,0.014439,0.023380,0.008370
pixel2,0.002292,0.007644,0.073446,0.190483,0.092206,0.063442,0.052486,0.050678,0.065414,0.108506,...,0.007670,0.064301,0.077482,0.024820,-0.062244,-0.028656,0.034298,0.067034,0.054005,0.012768
pixel3,-0.036650,0.007818,0.190483,1.494052,1.161682,0.621905,0.622762,0.611796,0.618777,0.865053,...,0.712569,0.999809,0.941965,0.331613,-0.242307,-0.082839,0.248304,0.279683,0.113755,0.040684
pixel4,-0.050100,0.010825,0.092206,1.161682,6.016476,6.055057,4.662224,4.895632,4.872622,4.980931,...,1.366851,2.240534,2.406719,1.802909,1.230760,1.117989,1.739163,0.528830,0.070578,0.043923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
pixel780,-8.680242,-0.010437,-0.028656,-0.082839,1.117989,4.181683,8.512155,10.023374,12.353301,26.709952,...,-193.232908,-20.124251,81.141671,668.350209,1848.900575,2038.433281,1002.171468,274.149030,75.449861,7.044752
pixel781,-1.534300,-0.000302,0.034298,0.248304,1.739163,3.312900,6.665027,7.411508,10.946284,24.095328,...,-72.169171,12.377488,56.433545,170.282844,674.232029,1002.171468,877.025241,332.734140,92.695406,8.424642
pixel782,2.278550,0.014439,0.067034,0.279683,0.528830,2.162690,4.479759,4.210016,5.571566,8.682649,...,-2.810097,28.956429,54.002425,70.872523,137.485565,274.149030,332.734140,302.673239,107.270039,8.340081
pixel783,1.611458,0.023380,0.054005,0.113755,0.070578,0.924510,1.682267,1.239537,0.782999,0.016454,...,1.021777,12.127410,21.286911,31.936785,49.013861,75.449861,92.695406,107.270039,87.551241,8.989483
pixel784,0.132942,0.008370,0.012768,0.040684,0.043923,0.065230,0.061411,0.031295,0.017721,0.014123,...,2.031082,2.948610,3.328791,4.155556,5.259276,7.044752,8.424642,8.340081,8.989483,4.519248

In [6]:
len(df.iloc[0])

785

In [7]:
df.var(axis=0)

label          8.250138
pixel1         0.008966
pixel2         0.073447
pixel3         1.494076
pixel4         6.016577
               ...
pixel780    2038.467256
pixel781     877.039858
pixel782     302.678284
pixel783      87.552700
pixel784       4.519324
Length: 785, dtype: float64