In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/zalando-research/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_test.csv
/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_train.csv
/kaggle/input/datasets/zalando-research/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/datasets/zalando-research/fashionmnist/train-images-idx3-ubyte

In [2]:
df = pd.read_csv("/kaggle/input/datasets/zalando-research/fashionmnist/fashion-mnist_train.csv")
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,1,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,8,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df = df-df.mean()
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,-2.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
1,4.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
2,1.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,2.801717,-5.682,...,-34.6254,-23.300683,-16.588267,12.130567,20.185183,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
3,-4.5,-0.0009,-0.00615,-0.035333,0.898067,1.752033,-0.411467,-0.805767,-2.198283,-5.682,...,-31.6254,-23.300683,-16.588267,-17.869433,-22.814817,-16.911483,-8.520633,-2.7533,-0.855517,-0.07025
4,-1.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,4.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59996,-3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,38.3746,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59997,3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,125.3746,138.699317,146.411733,117.130567,71.185183,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59998,3.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025
59999,2.5,-0.0009,-0.00615,-0.035333,-0.101933,-0.247967,-0.411467,-0.805767,-2.198283,-5.682,...,-34.6254,-23.300683,-16.588267,-17.869433,-22.814817,-17.911483,-8.520633,-2.7533,-0.855517,-0.07025

In [4]:
df.mean()

label       0.000000e+00
pixel1      2.442491e-19
pixel2     -7.105427e-19
pixel3     -4.381680e-18
pixel4     -4.357995e-17
                ...
pixel780   -7.351749e-16
pixel781   -1.008023e-15
pixel782   -7.389644e-17
pixel783    0.000000e+00
pixel784   -2.297422e-17
Length: 785, dtype: float64

In [5]:
c = (df.T@df)/len(df)-df.mean()@df.mean().T

In [6]:
lam,v=np.linalg.eigh(c)